spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.url=jdbc:mysql://localhost:3306/lojaweb?useTimezone=true&serverTimezone
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update		

spring.mvc.pathmatch.matching-strategy=ant-path-matcher

spring.mail.host=smtp.gmail.com
spring.mail.protocol=smtp
spring.mail.port=587
spring.mail.username=phillipageronimo@gmail.com
spring.mail.password=fveeebbpqfbghwlv
spring.mail.properties.mail.smtp.starttls.enable:true
spring.mail.properties.mail.smtp.auth=true
spring.mail.test-connection=true





